spring:
  kafka:
    consumer:
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            value:
              default:
                type: bertsanders.demo.kafka.model.CalculationInput
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
sample:
  consumer-topic-name: testing-input
  producer-topic-name: testing-output
logging:
  level:
    com:
      walmart:
        demo:
          kafka: debug
